// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO26wvLEjm2Wloy5KAWLckFErAu1EZCC4',
    appId: '1:928140561021:web:5f88b958771de1a596ff14',
    messagingSenderId: '928140561021',
    projectId: 'poker-tracker-b2659',
    authDomain: 'poker-tracker-b2659.firebaseapp.com',
    storageBucket: 'poker-tracker-b2659.firebasestorage.app',
    measurementId: 'G-4S4398XN1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDYa2vWlFULDU64jXasYd2yqf7d6t-sU',
    appId: '1:928140561021:android:9f10f8625c1550bb96ff14',
    messagingSenderId: '928140561021',
    projectId: 'poker-tracker-b2659',
    storageBucket: 'poker-tracker-b2659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKBjjr-_ciJNfUP6Xu4FZheTKRSX9hrs',
    appId: '1:928140561021:ios:3ef31977cc57990f96ff14',
    messagingSenderId: '928140561021',
    projectId: 'poker-tracker-b2659',
    storageBucket: 'poker-tracker-b2659.firebasestorage.app',
    iosClientId: '928140561021-8ti60dt5lhd70iovbm2i2tnqp1bra9fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokerTracker',
  );

}